# Generated by Django 4.1.4 on 2022-12-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, max_length=20)),
                ('title', models.TextField()),
                ('descripton', models.TextField()),
                ('catagory', models.TextField()),
                ('amount', models.FloatField()),
            ],
        ),
    ]
