# Generated by Django 4.1.4 on 2022-12-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='title',
            field=models.TextField(max_length=20),
        ),
    ]
