# Generated by Django 4.1.4 on 2022-12-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_expenses_date_alter_expenses_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='descripton',
            new_name='description',
        ),
    ]
